name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    name: Test on Go ${{matrix.go-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.24' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go ${{matrix.go-version}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}
        cache: true
    - name: Display Go version
      run: go version
    - name: Test
      run: GOMAXPROCS=1 go test -v ./...
  lint:
    name: Lint (Latest Go)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go (Latest)
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    - name: Lint
      run: go vet ./...
    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: 2025.1.1
        install-go: false
